server:
    port: 8443
    ssl:
        enabled: true
        key-store: "server.keystore.jks"
        key-store-password: javaexample
com:
    yoti:
        scenarioId: "yoti-scenario-id-from-dashboard"
        client:
            applicationId: "yoti-application-id-from-dashboard"
            clientSdkId: "yoti-client-sdk-id-from-dashboard"
            accessSecurityKey: "classpath:/key-file-from-dashboard.pem"
